//! Which part of a `UserPromptSubmit` prompt the user actually wrote.
//!
//! # Why this exists
//!
//! The hook's `prompt` field is one string, but it is not always one voice.
//! Claude Code clients prepend context of their own, and the hook flattens it
//! into the same field as the user's words:
//!
//! * the VS Code extension sends the editor's open file as a separate content
//!   block, `<ide_opened_file>The user opened the file … in the IDE. This may
//!   or may not be related to the current task.</ide_opened_file>`, and the
//!   hook delivers it glued to the front of what the user typed;
//! * finished background tasks arrive as a prompt consisting of nothing but a
//!   `<task-notification>` block;
//! * slash-command bookkeeping arrives as `<command-name>`, `<command-args>`,
//!   `<local-command-stdout>` and friends.
//!
//! Before v0.1.2 every one of these was an ordinary prompt to the intent rules.
//! A real VS Code session stored its ROOT as the IDE block followed by the
//! task, and the ladder's `first_message 240->160 chars` rung then kept the IDE
//! sentence and cut the task. On the same machine three `<task-notification>`
//! prompts had become a session's ROOT and thirty-three had superseded the
//! user's latest message.
//!
//! # The rule
//!
//! A block is *injected* when all of the following hold, and only then:
//!
//! 1. it is a complete element, `<name …>…</name>`, with a matching closing tag;
//! 2. it sits at the **edge** of the prompt: nothing but whitespace and other
//!    injected blocks lies between it and the start (or the end);
//! 3. its tag name belongs to a family that a client or Velra itself is known
//!    to generate ([`origin`]).
//!
//! Everything else is authored text, kept verbatim. The rule is deliberately
//! conservative, and the families are an explicit table rather than "any
//! leading tag", because a leading tag is not evidence of machine origin on its
//! own: the same client wraps a paste in `<pasted_content id="…">`, and that is
//! the user's own task text. An unknown tag, a tag in the middle of the prompt,
//! or an element that never closes therefore stays in the user's message.
//! Losing an injected sentence into the objective costs budget; losing the
//! user's words costs the objective.
//!
//! Nothing here changes what is stored in `events`: the raw prompt is kept as
//! delivered, so `velra inspect --trace` still finds an injected string at the
//! source and can say why it went no further.

/// Who generated an injected block.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Origin {
    /// Editor integration context (`<ide_opened_file>`, `<ide_selection>`, …).
    Ide,
    /// Claude Code's own machinery: reminders, task notifications, slash-command
    /// and shell-escape transcripts.
    Harness,
    /// A record Velra itself produced (`<VELRA_WORKSPACE_STATE>`,
    /// `<VELRA_CONTINUATION>`), pasted or echoed back into a prompt. Treating it
    /// as the user's objective would make the next capsule quote the last one.
    Velra,
}

impl Origin {
    pub fn as_str(self) -> &'static str {
        match self {
            Origin::Ide => "IDE context",
            Origin::Harness => "client metadata",
            Origin::Velra => "a Velra record",
        }
    }
}

/// Harness tags matched exactly.
const HARNESS_TAGS: &[&str] = &[
    "system-reminder",
    "task-notification",
    "user-prompt-submit-hook",
];

/// Harness tag families, matched by prefix: `command-name` / `command-message`
/// / `command-args` for slash commands, `local-command-stdout` / `-stderr` /
/// `-caveat` for their output, `bash-input` / `bash-stdout` / `bash-stderr` for
/// the `!` shell escape.
const HARNESS_FAMILIES: &[&str] = &["command-", "local-command-", "bash-"];

/// The family a tag name belongs to, or `None` when it is not known to be
/// generated by anything but the user. Case-insensitive.
pub fn origin(tag: &str) -> Option<Origin> {
    let t = tag.to_ascii_lowercase();
    if t.starts_with("ide_") || t.starts_with("ide-") {
        return Some(Origin::Ide);
    }
    if t.starts_with("velra_") {
        return Some(Origin::Velra);
    }
    if HARNESS_TAGS.contains(&t.as_str()) || HARNESS_FAMILIES.iter().any(|f| t.starts_with(f)) {
        return Some(Origin::Harness);
    }
    None
}

/// One injected block removed from a prompt.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Injected<'a> {
    pub tag: &'a str,
    pub origin: Origin,
    /// The whole element, tags included.
    pub text: &'a str,
}

/// A prompt split into what the user wrote and what was injected around it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PromptParts<'a> {
    /// The user's own text, trimmed. Empty when the prompt was nothing but
    /// injected context.
    pub authored: &'a str,
    /// Injected blocks, leading ones first (in order), then trailing ones.
    pub injected: Vec<Injected<'a>>,
}

fn is_name_start(c: u8) -> bool {
    c.is_ascii_alphabetic()
}

fn is_name_char(c: u8) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, b'_' | b'-' | b':')
}

/// Longest opening tag, attributes included, that is looked at. An opening tag
/// is short; anything longer is prose that happens to contain `<`.
const MAX_OPEN_TAG: usize = 512;

/// A complete element at the very start of `s` (no leading whitespace):
/// `(tag name, byte length of the whole element)`.
fn element_at_start(s: &str) -> Option<(&str, usize)> {
    let b = s.as_bytes();
    if b.first() != Some(&b'<') || !b.get(1).copied().is_some_and(is_name_start) {
        return None;
    }
    let mut i = 1;
    while i < b.len() && is_name_char(b[i]) {
        i += 1;
    }
    let name = &s[1..i];
    // The opening tag ends at the first `>`; it may carry attributes, but not
    // another `<`, and not more than MAX_OPEN_TAG bytes.
    let rest = &s[i..];
    let close_open = rest.find('>')?;
    if close_open > MAX_OPEN_TAG || rest[..close_open].contains('<') {
        return None;
    }
    // Attributes must be separated from the name by whitespace.
    if close_open > 0 && !rest.as_bytes()[0].is_ascii_whitespace() && rest.as_bytes()[0] != b'/' {
        return None;
    }
    let body_start = i + close_open + 1;
    let closing = format!("</{name}>");
    let end = s[body_start..].find(&closing)? + body_start + closing.len();
    Some((name, end))
}

/// A complete element at the very end of `s` (no trailing whitespace):
/// `(tag name, byte offset where the element starts)`.
fn element_at_end(s: &str) -> Option<(&str, usize)> {
    let close_start = s.rfind("</")?;
    let tail = &s[close_start + 2..];
    let name = tail.strip_suffix('>')?;
    let nb = name.as_bytes();
    if nb.is_empty() || !is_name_start(nb[0]) || !nb.iter().all(|&c| is_name_char(c)) {
        return None;
    }
    // The nearest opening tag of the same name before the closing one.
    let head = &s[..close_start];
    let mut search = head.len();
    while let Some(at) = head[..search].rfind(&format!("<{name}")) {
        if let Some((n, len)) = element_at_start(&s[at..]) {
            if n == name && at + len == s.len() {
                return Some((name, at));
            }
        }
        search = at;
    }
    None
}

/// Splits `raw` into the user's own text and the injected blocks at its edges.
pub fn split(raw: &str) -> PromptParts<'_> {
    let mut injected = Vec::new();
    let mut start = 0usize;
    let mut end = raw.len();

    loop {
        let rest = &raw[start..end];
        let trimmed = rest.trim_start();
        let offset = start + (rest.len() - trimmed.len());
        let Some((tag, len)) = element_at_start(trimmed) else {
            break;
        };
        let Some(origin) = origin(tag) else {
            break;
        };
        injected.push(Injected {
            tag,
            origin,
            text: &raw[offset..offset + len],
        });
        start = offset + len;
    }
    let mut trailing = Vec::new();
    loop {
        let rest = &raw[start..end];
        let trimmed = rest.trim_end();
        let stop = start + trimmed.len();
        let Some((tag, at)) = element_at_end(trimmed) else {
            break;
        };
        let Some(origin) = origin(tag) else {
            break;
        };
        trailing.push(Injected {
            tag,
            origin,
            text: &raw[start + at..stop],
        });
        end = start + at;
    }
    trailing.reverse();
    injected.extend(trailing);
    PromptParts {
        authored: raw[start..end].trim(),
        injected,
    }
}

/// The user's own text of a prompt; see [`split`].
pub fn authored(raw: &str) -> &str {
    split(raw).authored
}

#[cfg(test)]
mod tests {
    use super::*;

    const IDE: &str = "<ide_opened_file>The user opened the file c:\\repo\\readme.md in the IDE. \
                       This may or may not be related to the current task.</ide_opened_file>";

    #[test]
    fn a_vs_code_open_file_block_is_not_the_users_text() {
        let raw = format!("{IDE}\nWe have a failing payment retry test. Fix it.");
        let parts = split(&raw);
        assert_eq!(
            parts.authored,
            "We have a failing payment retry test. Fix it."
        );
        assert_eq!(parts.injected.len(), 1);
        assert_eq!(parts.injected[0].tag, "ide_opened_file");
        assert_eq!(parts.injected[0].origin, Origin::Ide);
        assert_eq!(parts.injected[0].text, IDE);
    }

    #[test]
    fn several_leading_blocks_and_a_selection_are_all_removed() {
        let raw = format!(
            "{IDE} <ide_selection>The user selected the lines 3 to 4 from x.py:\nretry()\n</ide_selection>\n\n  fix the retry"
        );
        let parts = split(&raw);
        assert_eq!(parts.authored, "fix the retry");
        let tags: Vec<&str> = parts.injected.iter().map(|i| i.tag).collect();
        assert_eq!(tags, ["ide_opened_file", "ide_selection"]);
    }

    #[test]
    fn a_prompt_that_is_only_injected_context_has_no_authored_text() {
        for raw in [
            "<task-notification>\n<task-id>b1</task-id>\n<status>completed</status>\n</task-notification>",
            "<command-name>/compact</command-name>\n<command-message>compact</command-message>\n<command-args></command-args>",
            "<local-command-stdout>Compacted </local-command-stdout>",
            IDE,
            "<VELRA_CONTINUATION v=\"1\" checkpoint=\"c\">state</VELRA_CONTINUATION>",
        ] {
            assert_eq!(split(raw).authored, "", "{raw}");
        }
    }

    #[test]
    fn user_authored_wrappers_and_unknown_tags_are_kept() {
        // A paste is the user's own task text, wrapped by the client.
        let paste = "<pasted_content id=\"2559\">\nWe are working in the Velra repository.\n</pasted_content id=\"2559\">";
        assert_eq!(split(paste).authored, paste);
        let raw = format!("{IDE}\n{paste}");
        assert_eq!(split(&raw).authored, paste);
        // A tag the user wrote themselves.
        let own = "<example>input</example> should parse as a list";
        assert_eq!(split(own).authored, own);
        let own = "<b>fix</b>";
        assert_eq!(split(own).authored, own);
    }

    #[test]
    fn only_the_edges_are_considered() {
        // Quoted in the middle of the message: the user is talking about it.
        let raw = "why does <system-reminder>x</system-reminder> show up in my prompt?";
        assert_eq!(split(raw).authored, raw);
        // A trailing reminder is removed; the question stays.
        let raw = "what failed? <system-reminder>be brief</system-reminder>";
        let parts = split(raw);
        assert_eq!(parts.authored, "what failed?");
        assert_eq!(parts.injected[0].tag, "system-reminder");
    }

    #[test]
    fn malformed_or_unclosed_blocks_are_kept() {
        for raw in [
            "<ide_opened_file>The user opened a file and the tag never closes. fix it",
            "<ide_opened_file The user forgot the bracket</ide_opened_file> fix it",
            "<ide_opened_file>a</ide_selection> fix it",
            "< ide_opened_file>a</ide_opened_file> fix it",
            "<1abc>a</1abc> fix it",
        ] {
            assert_eq!(split(raw).authored, raw.trim(), "{raw}");
        }
    }

    #[test]
    fn slash_commands_and_prefixes_after_an_ide_block_are_seen() {
        let raw = format!("{IDE}\ntask: migrate the settings loader");
        assert_eq!(split(&raw).authored, "task: migrate the settings loader");
        let raw = format!("{IDE}\n/compact");
        assert_eq!(split(&raw).authored, "/compact");
    }

    #[test]
    fn families_are_matched_case_insensitively_and_by_prefix() {
        assert_eq!(origin("ide_diagnostics"), Some(Origin::Ide));
        assert_eq!(origin("IDE_Selection"), Some(Origin::Ide));
        assert_eq!(origin("bash-stdout"), Some(Origin::Harness));
        assert_eq!(origin("local-command-caveat"), Some(Origin::Harness));
        assert_eq!(origin("VELRA_WORKSPACE_STATE"), Some(Origin::Velra));
        assert_eq!(origin("pasted_content"), None);
        assert_eq!(origin("idea"), None);
        assert_eq!(origin("commander"), None);
    }

    /// The hook's worst case: a prompt at the 4 KiB cap made of nothing but
    /// near-miss openings before a closing tag. Every candidate is examined and
    /// rejected; nothing is removed.
    #[test]
    fn a_pathological_prompt_is_kept_whole() {
        let raw = format!("{}</ide_x>", "<ide_x".repeat(680));
        assert!(raw.len() <= 4 * 1024);
        assert_eq!(split(&raw).authored, raw);
        let raw = format!("{}x", "<ide_x>".repeat(585));
        assert_eq!(split(&raw).authored, raw);
    }

    proptest::proptest! {
        /// Fail-open: whatever arrives, splitting never panics, the authored
        /// part is a trimmed slice of the input, and splitting it again removes
        /// nothing more at the edges than the first pass left.
        #[test]
        fn splitting_never_panics_and_only_removes_edges(
            raw in "(<(ide_opened_file|system-reminder|task-notification|pasted_content|b)( id=\"1\")?>|</(ide_opened_file|system-reminder|task-notification|pasted_content|b)>|[a-z ]{0,6}|\u{e9}|\n){0,24}"
        ) {
            let parts = split(&raw);
            proptest::prop_assert!(raw.contains(parts.authored));
            proptest::prop_assert_eq!(parts.authored, parts.authored.trim());
            for block in &parts.injected {
                proptest::prop_assert!(raw.contains(block.text));
                proptest::prop_assert!(origin(block.tag).is_some());
            }
        }
    }

    #[test]
    fn plain_prompts_are_untouched() {
        for raw in ["", "   ", "fix the login bug", "a < b and c > d", "x</y>"] {
            assert_eq!(split(raw).authored, raw.trim());
            assert!(split(raw).injected.is_empty());
        }
    }
}
